@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.common;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;