@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.common.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;