@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.refinement_test.common.block.entity;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;