@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.client.proxy;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;