@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.client.model;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;