@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.client.model;

import javax.annotation.ParametersAreNonnullByDefault;
import mcp.MethodsReturnNonnullByDefault;