@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.refinement.common.network;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;