@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.common.proxy;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;