@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package ninjaphenix.expandedstorage.common.block.enums;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;