@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.refinement_test.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;