@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.refinement_test.client;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;