@ParametersAreNonnullByDefault @MethodsReturnNonnullByDefault
package ninjaphenix.refinement.impl.common;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;